### ISSUE TITLE
Possible to read cell background color?

### ISSUE THREAD

**Issue by michaelaguiar** [nuovo/spreadsheet-reader#102]
I am looking through and I see functions for Styles, but can't seem to call them?  Is this not possible?

**Comment by RanveerSinghRockss** [comment]
Even i am looking for the properties of the sheet. I tried accessing it but was not successful. When we use print_r() for the XLS file it shows all the properties of the file for each cells, but when been used for other files such as XLSX,ODS and CSV it does not show anything apart from the data it has.
