### ISSUE TITLE
dead project?

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [nuovo/spreadsheet-reader#158]
Is someone still updating on this repo?
Which lib could be used instead to read xlsx files in PHP?

**Comment by jorix** [comment]
Now I try a PR to @fujaru as fujaru#3

It seems that [fujaru/spreadsheet-reader](https://github.com/fujaru/spreadsheet-reader) he has gone a little way (works on PH7.2) and pick up some PR,  
to see if he picks it up the third...

**Comment by Flex301** [comment]
@alexplusde I'm looking at the [PHPOffice/PhpSpreadsheet](https://github.com/PHPOffice/PhpSpreadsheet) now. Seems like it's alive.
