### ISSUE TITLE
issue with PHP spreadsheet reader 

### ISSUE THREAD

**Issue by ekansh1** [nuovo/spreadsheet-reader#18]
I am facing one issue with PHP spreadsheet reader https://github.com/nuovo/spreadsheet-reader , it is reading all formats file except **.xlsx** , in case of .xlsx script was not running

```
require($docroot.'/inc/filereader/excel_reader2.php');
require($docroot.'/inc/SpreadsheetReader.inc.php');             
$Spreadsheet = new SpreadsheetReader("filepath");
```

When i am executing php script at my localhost, SpreadsheetReader reading .xlsx file and returning desired result, but when i am trying to run same code on some server then it is only executing for(.csv,.xls,.txt) but not for .xlsx.

I have already checked folder and file permissions for above issue at server.

**Comment by Dineshkumar05** [comment]
in xlsx file the datetime format is 4-1-2010 12:10:00 but after reading the file it gives 4-1-2010 01:00:00
i am using create date and date_format function. i need what shows in excel that only reflects after reading the xlsx file..
please ans me.....?
