### ISSUE TITLE
XLSX rewind does not actually rewind

### ISSUE THREAD

**Issue by osuwariboy** [nuovo/spreadsheet-reader#50]
Hi there,

I've discovered that when you load a XLSX sheet and do this:

$file->next()
$file->rewind()
print_r($file->current())

The row that's printed is actually the second row, not the first as I would expect. That's because the rewind() function never sets the CurrentRow property back to false. I added the slight correction and everything started working as it should.

I hope this helps,

Osu

**Comment by pilsetnieks** [comment]
Thanks, this is fixed in v.0.5.8.
