### ISSUE TITLE
Read inline cell value

### ISSUE THREAD

**Issue by dimapashkov** [nuovo/spreadsheet-reader#52]
I am using Apache POI (Java) to generate xlsx files. POI library writes data inline, so in my case reader always return empty rows.
Cell generated with POI:
```xml
<c r="A1" t="inlineStr">
	<is>
		<t>SOME TEXT</t>
	</is>
</c>
```

I solved this by adding one more case to next function:
```php
public function next()
{
	...
	// Cell value
	case 'is':
	case 'v':
		if ($this -> Worksheet -> nodeType == XMLReader::END_ELEMENT)
...
```

**Comment by pilsetnieks** [comment]
Thanks, this is partly fixed in v.0.5.8. I still have to sort out the sheet changing part, though.
