### ISSUE TITLE
Implement SeekableIterator

### ISSUE THREAD

**Issue by paales** [nuovo/spreadsheet-reader#54]
See documentation: http://nl3.php.net/SeekableIterator

Our current use case requires the implementation of SeekableIterator. I'm willing to create a pull request for this. Any suggestions on implementing it?

**Comment by pilsetnieks** [comment]
This was implemented in v.0.5.10. (https://github.com/nuovo/spreadsheet-reader/commit/493ccd46acfa940b8f1d5c5f924f4b3ccda663de). Thanks for your suggestion and for your pull request.
