### ISSUE TITLE
ChangeSheet not doing anything for XLSX

### ISSUE THREAD

**Issue by osuwariboy** [nuovo/spreadsheet-reader#60]
Hey there,

      When you open an XLSX file and call ChangeSheet as your first operation, ChangeSheet will not change the sheet. This is because of the following condition in the rewind method:

if ($this -> Index > 0 || !($this -> Worksheet instanceof XMLReader))

This is because, if you haven't done anything, 

$this->Index is 0 and $this->Worksheet is indeed an instance of XMLReader since the first sheet was loaded. So to fix this, either unset $this->Worksheet or set $this->Index to 1 in the ChangeSheet method, this way, rewind will successfully load the correct worksheet when it's called.

**Comment by pilsetnieks** [comment]
Thanks, this is fixed in v.0.5.8.
