### ISSUE TITLE
ChangeSheet doesn't work

### ISSUE THREAD

**Issue by mn1aC** [nuovo/spreadsheet-reader#72]
I have the following code from the example:

foreach ($Sheets as $Index => $Name)
    {
        echo 'Sheet #'.$Index.': '.$Name;
        $Reader->ChangeSheet($Index);
        echo "<br/> change sheet";
        foreach ($Reader as $rowData) {
        	print_r($rowData);
        }
    }

output: 
Sheet #0: cash
Sheet #1 : others

put the printout of (print_r) gives twice the rows of Sheet #1:others.... ?? Weird??

**Comment by pilsetnieks** [comment]
Thanks, this has been incorporated in v.0.5.8. now.

**Comment by sergiomeneses** [comment]
Hi this still happens in v.0.5.10, i need this working, any new about it?

**Comment by sergiomeneses** [comment]
Hi this is fixed by apply the update in the following issue: https://github.com/nuovo/spreadsheet-reader/issues/59#issuecomment-40710172
