### ISSUE TITLE
Semantic Versioning via Git Tags

### ISSUE THREAD

**Issue by janhartigan** [nuovo/spreadsheet-reader#87]
I noticed you guys are keeping version numbers in the composer.json file, but I'm not sure if you're aware that this isn't translating to packagist. Have a look at your packagist page:

https://packagist.org/packages/nuovo/spreadsheet-reader

It only shows the two branches as being available and no versions. This makes it difficult to track dependencies to old versions of this library. Really easy fix for this is to tag releases with the semantic version whenever you make a version bump. For example, this commit:

https://github.com/nuovo/spreadsheet-reader/commit/493ccd46acfa940b8f1d5c5f924f4b3ccda663de

You would run:

```bash
git tag -a v0.5.10 -m "Version 0.5.10"

git push --tags
```

It would then show up in your tags and you could (optionally) create a release for the new version. So long as they follow the semantic versioning syntax, packagist will understand it.

Take a look at the tags of one of my libraries: https://github.com/FrozenNode/Laravel-Administrator/tags

And then notice how it looks on Packagist: https://packagist.org/packages/frozennode/administrator

This makes it possible to track an older version by doing this in your composer.json:

```json
"frozennode/administrator": "4.*"
```

**Comment by pilsetnieks** [comment]
Thank's, I've taken it into account. I wasn't sure about how Packagist would handle it since someone else had added the library there and I don't have control over it there but it seems that it works just fine.
