### ISSUE TITLE
Dates Issue

### ISSUE THREAD

**Issue by joebirkin** [nuovo/spreadsheet-reader#97]
I'm so glad I spent ages integrating this into a data import system only to find out it renders date fields so they're unusable.

Might be something worth fixing for other people. I'm just getting 5 digit integers.

**Comment by joebirkin** [comment]
So apparently this is an XLSX thing - would probably be worth mentioning somewhere in the docs...

**Comment by casperbakker** [comment]
@hodephinitely Maybe you need to be a bit more friendly and helpful to a free and open source project like this one. It is possible you're just the first one to try this situation...

If you could explain what went wrong and how you fixed it. Even better if you type the appropriate docs in 2-3 paragraphs. Then it can be included in the docs for the next person trying the same thing as you did.

**Comment by pilsetnieks** [comment]
Posting the problematic file would also be helpful

**Comment by JasonBaier** [comment]
Those are Excel dates... I've seen them as integers and floats. You can convert them to Unix date format easily. Here's a simple function to format dates while it detects the format:

``` php
/**
 * Validate and format a date/time
 *
 * @param  $format   : format to convert to (Ex: 'Y-m-d')
 * @param  $datetime : original date or date/time - NOT Unix time
 * @return formatted date/datetime | FALSE
 */
function format_date($format, $datetime)
{
    if (is_float($datetime) || is_int($datetime))
    {
        // convert Excel date/time to Unix, then format
        return date($format, ($datetime - 25569) * 86400);
    }
    else
    {
        return date($format, strtotime($datetime));
    }
}
```

I only learned of this because PHPExcel has a function for handling this: PHPExcel_Shared_Date::ExcelToPHP

**Comment by joebirkin** [comment]
Sorry - I was having a bad day. I managed to sort it using something similar to the above. I've since switched to an alternative solution anyway.
