### ISSUE TITLE
getting junk in cells and rows for xls file

### ISSUE THREAD

**Issue by rodnikosh** [nuovo/spreadsheet-reader#98]
i created an xls file with two words: "hello" in one column and "me" in another and saved.
i tried to use the  component to analyase it and got junk in many cells.
i attached a picture of the log file i write the cell content into.

also weird is that i had only two words in two columns, and i get junk on about 30 or 40 cells.

my code is:

require('modules/InboundEmail/spreadsheet-reader-master/php-excel-reader/excel_reader2.php');

require('modules/InboundEmail/spreadsheet-reader-master/SpreadsheetReader.php');

$Reader = new SpreadsheetReader($filePathInUpload);

foreach ($Reader as $Row)
{
    foreach($Row as $cell)
    {
        $GLOBALS['log']->fatal("cell = " . $cell);
    }
}

anyone have an idea?

![junk](https://cloud.githubusercontent.com/assets/13796542/9272836/ff70321e-428e-11e5-8624-6e0436548cc7.JPG)

**Comment by pilsetnieks** [comment]
It's hard to say anything without the actual file to look at. Can you post the file somewhere to see what the issue is?

**Comment by rodnikosh** [comment]
Thank you for the quick reply.
i tried to post it here , but it only receive image files.

The file is a very simple and basic excel file made with Office 2007 Excel.
just made a new Excel sheet and saved it as xls. thats it...

in order to attach it here, i renamed the xls file extension to "jpg" and added it here as attachment. so just rename it back to xls.

![reporttocrm_subs_onerow](https://cloud.githubusercontent.com/assets/13796542/9273482/d412bf40-4295-11e5-8c75-70f255ed0621.jpg)

**Comment by pilsetnieks** [comment]
It looks like the file is treated as a text file when uploaded. When I try reading the file from disk, it works fine. It seems that when the file is uploaded, you use the `tmp_name` as the file path which doesn't give any clue as to the file type, and the library defaults to TXT/CSV instead of XLS.

There are two more parameters to the constructor, I'd suggest setting them as well:

```
public function __construct($Filepath, $OriginalFilename = false, $MimeType = false)
```

something like this:

```
$Reader = new SpreadsheetReader($_FILES['file']['tmp_name'], $_FILES['file']['name'], $_FILES['file']['type']);
```

Those two additional parameters would give more clues as to what type of file it is.

**Comment by rodnikosh** [comment]
ok, thanks, i will try what you wrote.
The file in the system, is indeed called upload/1ae68738-71bb-f6c3-1b84-55af4d759d7b 
and not upload/1ae68738-71bb-f6c3-1b84-55af4d759d7b.xls

i will rename it in the code and add the ".xls" before using the constructor.

will update....

**Comment by rodnikosh** [comment]
Yes, it solved the problem.
i added an ".xls" at the end of the file that the system uploads and its working.
thank you!
